services:
  adminer:
    image: adminer:4.8.1
    container_name: dealnews_adminer
    ports:
      - "8081:8080"
    restart: unless-stopped

  scraper:
    build: .
    container_name: dealnews_scraper
    env_file:
      - .env
    environment:
      - MYSQL_HOST=laradock-mysql-1
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=dealnews
    volumes:
      - ./exports:/app/exports
    depends_on:
      - adminer
    command: ["python", "run.py"]
    restart: "no"